sept_tadelles/leaderboard/urls.py
from django.urls import path

from . import views

app_name = "leaderboard"
urlpatterns = [

	path("partie/create", views.partie_create, name="partie_create"),
	path("partie/list", views.partie_list, name="partie_list"),
	path("partie/detail", views.partie_detail, name="partie_detail"),
	path("partie/done", views.partie_terminer, name="partie_terminer"),
	path("partie/undo", views.partie_annuler, name="partie_annuler"),

	path('index', views.index, name="index"),
	path('reset-all-scores', views.reset_all_scores, name="reset_all_scores"),
]

sept_tadelles/sept_tadelles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('welcome.urls')),
    path('wiki/', include('wiki.urls')),
    path('account/', include('account.urls')),
    path('soiree/', include('soiree.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sept_tadelles/wiki/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:game_id>/", views.detail, name="detail"),
]

sept_tadelles/leaderboard/models.py
from django.db import models

from wiki import models as wiki_models

from account import models as account_models



class Partie(models.Model) :

	creator = models.ForeignKey(
		account_models.User,
		related_name = "parties_owned",
		on_delete = models.SET_NULL,
		null=True,
		blank = True
	)

	jeu = models.ForeignKey(
		wiki_models.Game,
		verbose_name = "Jeu",
		on_delete = models.CASCADE
	)

	joueurs = models.ManyToManyField(
		account_models.User,
		related_name = "parties",
		blank = True
	)

	classement = models.ManyToManyField(
		account_models.User,
		through = 'PositionJoueur',
		blank = True
	)

	finie = models.BooleanField(default=False)

	current_month = models.BooleanField(default=True)

	created_at = models.DateTimeField(
        verbose_name="Created at",
        null=True,
        blank=True
    )




class PositionJoueur(models.Model) :

	positionjoueur_id = models.BigAutoField(primary_key=True)

	joueur = models.ForeignKey(
		account_models.User,
		on_delete = models.CASCADE,
		related_name = 'position'
	)

	partie = models.ForeignKey(
		Partie,
		on_delete = models.CASCADE
	)

	position = models.PositiveIntegerField()

sept_tadelles/leaderboard/forms.py
from django import forms

from . import models
from wiki import models as wiki_models
from account import models as account_models

class PartieCreationForm(forms.Form) :
	filter_horizontal = ('joueurs',)

	jeu = forms.ModelChoiceField(
		label = "Jeu",
		queryset = wiki_models.Game.objects.filter(ranking=True)
	)

	joueurs = forms.ModelMultipleChoiceField(
		label = "Joueurs",
		queryset = account_models.User.objects.filter(discord_verified=True),
		required = False
	)



class PartieClassementForm(forms.Form) :

	def __init__(self, request, partie, *args, **kwargs) :
		super(PartieClassementForm, self).__init__(*args, **kwargs)
		
		for i,joueur in enumerate(partie.joueurs.all()) :

			if joueur in partie.classement.all() :
				initial = models.PositionJoueur.objects.get(partie=partie, joueur=joueur).position
			else :
				initial = 1

			self.fields[f"{partie.joueurs.all()[i]}"] = forms.IntegerField(
				label=f"{partie.joueurs.all()[i]}",
				initial = initial,
				min_value = 1,
				max_value = len(partie.joueurs.all())
			)

sept_tadelles/leaderboard/views.py
from django.contrib import admin as django_admin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.urls import reverse
import json

import datetime as dt

from . import forms, models, admin
from account.views import helpers

from wiki import models as wiki_models
from account import models as account_models

@login_required
def index(request) :

	if request.user.discord_verified :

		current_view = ['leaderboard:index', []]

		stats = {}
		classements = {
			'global': []
		}
		records = {
			'global': []
		}
		
		games = wiki_models.Game.objects.filter(ranking=True)
		players = account_models.User.objects.filter(discord_verified=True)

		for player in players :
			stats[player.username] = {
				'global_score': 0
			}
			for game in games :
				stats[player.username][game.name] = {
					'nb_parties': 0,
					'score': 0,
					**{str(position): 0 for position in range(1, game.players_max+1)},
				}
				for partie in player.parameters['month_games'][game.name] :
					stats[player.username][game.name]['nb_parties'] += 1
					stats[player.username][game.name][str(partie[1])] += 1
					stats[player.username][game.name]['score'] += 1.0*(partie[2]-(partie[1]-1))
					if partie[1] == 1 :
						stats[player.username][game.name]['score'] += 0.5*(partie[2]-(partie[1]-1))
				stats[player.username]['global_score'] += stats[player.username][game.name]['score']

		for player in players :
			classements['global'].append((player, stats[player.username]['global_score']))
			records['global'].append((player, player.parameters['records']['global']))
		classements['global'] = sorted(classements['global'], key=lambda x: x[1])[::-1]
		records['global'] = sorted(records['global'], key=lambda x: x[1])[::-1]

		for game in games :
			classements[game.name] = sorted([(player, stats[player.username][game.name]['score']) for player in players], key=lambda x: x[1])[::-1]
			records[game.name] = sorted([(player, player.parameters['records'][game.name]) for player in players], key=lambda x: x[1])[::-1]

		helpers.register_view(request, current_view)
		return render(request, 'leaderboard/index.html', {
			'games': games,
			'players': players,
			'classements': classements,
			'records' : records,
			'actions': helpers.get_actions(request),
		})

	else :
		return redirect('account:retour1')

@login_required
def reset_all_scores(request) :

	if request.user.username == settings.SITE_OWNER_PSEUDO :
		for joueur in account_models.User.objects.filter(discord_verified=True) :
			joueur.parameters.pop('month_games')
			joueur.parameters.pop('all_games')
			joueur.parameters.pop('records')
			joueur.save()
	return redirect('account:retour1')

@login_required
def partie_list(request) :

	if admin.PartieAdmin(models.Partie, django_admin.site).has_view_permission(request) :

		filtre = request.GET.get('filter', 'all') # done, open, all
		current_view = [f"{reverse('leaderboard:partie_list')}?filter={filtre}", []]
		if filtre == 'all' :
			filtre = 'done+open'

		parties = models.Partie.objects.none()
		if 'done' in filtre :
			parties = parties.union(models.Partie.objects.filter(creator=request.user).filter(finie=True))
		if 'open' in filtre :
			parties = parties.union(models.Partie.objects.filter(creator=request.user).filter(finie=False))

		parties = parties.order_by("-created_at")

		helpers.register_view(request, current_view)
		return render(request, 'leaderboard/partie/list.html', {
			'parties': parties,
			'actions': helpers.get_actions(request),
		})

	else :
		return render(request, 'leaderboard/error.html', {'error_txt': "Vous n'avez pas la permission de voir les parties."})

@login_required
def partie_detail(request) :

	partie_id = request.GET.get('id', False)

	current_view = [f"{reverse('leaderboard:partie_detail')}{f'?id={partie_id}' if partie_id else ''}", []]

	if partie_id :

		try :
			partie = models.Partie.objects.get(pk=partie_id)
		except :
			partie = None

		positions = {joueur: 0 for joueur in partie.joueurs.all()}
		for joueur in partie.classement.all() :
			positions[joueur] = models.PositionJoueur.objects.get(partie=partie, joueur=joueur).position

		if admin.PartieAdmin(models.Partie, django_admin.site).has_change_permission(request, partie) and partie.current_month :

			if not(partie.finie) :

				form = forms.PartieClassementForm(request, partie)
				if request.method == "POST" :
					form = forms.PartieClassementForm(request, partie, request.POST)
					if form.is_valid() :

						# on supprime les PositionJoueurs s'ils existent déjà
						positions_joueur = models.PositionJoueur.objects.filter(partie=partie)
						for position_joueur in positions_joueur :
							position_joueur.delete()
						
						# on range les joueurs dans l'ordre
						joueurs = []
						for i in range(1,len(partie.joueurs.all())+1) :
							for joueur in partie.joueurs.all() :
								if form.cleaned_data[f"{joueur}"] == i :
									joueurs.append(joueur)
						partie.joueurs.set(joueurs)
						partie.save()

						for joueur in partie.joueurs.all() :
							models.PositionJoueur.objects.create(partie=partie, joueur=joueur, position=form.cleaned_data[f"{joueur}"])
						
					return render(request, 'leaderboard/partie/detail_change.html', {
						'form': form,
						'partie': partie,
						'positions' :positions,
						'actions': helpers.get_actions(request),
					})

				helpers.register_view(request, current_view)
				return render(request, 'leaderboard/partie/detail_change.html', {
					'form': form,
					'partie': partie,
					'positions' :positions,
					'actions': helpers.get_actions(request),
				})

			else :

				helpers.register_view(request, current_view)
				return render(request, 'leaderboard/partie/detail_view.html', {
					'partie': partie,
					'positions' :positions,
					'actions': helpers.get_actions(request),
				})

		elif admin.PartieAdmin(models.Partie, django_admin.site).has_view_permission(request, partie) :

			helpers.register_view(request, current_view)
			return render(request, 'leaderboard/partie/detail_view.html', {
				'partie': partie,
				'positions' :positions,
				'actions': helpers.get_actions(request),
			})

		else :
			return render(request, 'leaderboard/error.html', {'error_txt': "Vous n'avez pas la permission de voir cette partie"})

	else :
		return redirect('account:retour1')


@login_required
def partie_terminer(request) :

	partie_id = request.GET.get('id', False)

	if partie_id :

		try :
			partie = models.Partie.objects.get(pk=partie_id)
		except :
			partie = None

		if admin.PartieAdmin(models.Partie, django_admin.site).has_change_permission(request, partie) :

			if partie.current_month :

				if not(partie.finie) :

					if len(partie.classement.all()) == len(partie.joueurs.all()) :

						for joueur in partie.classement.all() :
							position = models.PositionJoueur.objects.get(partie=partie, joueur=joueur).position
							joueur.parameters['month_games'][partie.jeu.name].append((partie.id,position,len(partie.joueurs.all())))
							joueur.save()

						partie.finie = True
						partie.save()

			else :

				partie.finie = True
				partie.save()

	return redirect('account:retour1')

@login_required
def partie_annuler(request) :
	
	partie_id = request.GET.get('id', False)

	if partie_id :

		try :
			partie = models.Partie.objects.get(pk=partie_id)
		except :
			partie = None

		if admin.PartieAdmin(models.Partie, django_admin.site).has_change_permission(request, partie) and partie.current_month :

			if partie.finie :

				for joueur in partie.classement.all() :
					for result in joueur.parameters['month_games'][partie.jeu.name] :
						if result[0] == partie.id :
							joueur.parameters['month_games'][partie.jeu.name].remove(result)
					joueur.save()

				partie.finie = False
				partie.save()

	return redirect('account:retour1')

@login_required
def partie_create(request) :

	current_view = ['leaderboard:partie_create', []]

	if request.user.username == settings.SITE_OWNER_PSEUDO :
		
		form = forms.PartieCreationForm()
		if request.method == "POST" :
			form = forms.PartieCreationForm(request.POST)
			if form.is_valid() :
				partie = models.Partie(
					creator = request.user,
					jeu = form.cleaned_data['jeu'],
					finie = False,
					created_at = dt.datetime.now()
				)
				partie.save()
				partie.joueurs.set(form.cleaned_data['joueurs'])
				partie.save()

				return redirect('account:retour1')

		#helpers.register_view(request, current_view)
		return render(request, 'leaderboard/partie/creation.html', {'form': form})

	else :
		return render(request, 'leaderboard/error.html', {'error_txt' : "Vous n'avez pas la permission de créer une Partie"})

sept_tadelles/leaderboard/templates/leaderboard/partie/creation.html
{% extends 'leaderboard/base_form.html' %}


{% load static %}


{% block extra_headers %}
{% endblock %}

{% block title %}
{% endblock %}

{% block pre-text %}
{% endblock %}

{% block errors %}
	{% for error_name, value in errors.items %}
		{% if value.0 %}
			<p>{{ value.1 }}</p>
		{% endif %}
	{% endfor %}
{% endblock %}

{% block form %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-default btn-lg" value="Créer la partie">
</form>
{% endblock %}

{% block post-text %}
{% endblock %}

sept_tadelles/leaderboard/templates/leaderboard/partie/detail_change.html
{% extends 'leaderboard/base.html' %}


{% load static %}


{% block base_headers %}
	<link rel="stylesheet" type="text/css" href="{% static 'leaderboard/css/partie/detail_change.css' %}">
{% endblock %}

{% block base_foreground %}
	<div class="foreground__heading"><h2>Partie de {{ partie.jeu }} créée à {{partie.created_at }}</h2></div>
	<div class="foreground__content">
		<form class="joueurs" action="" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" class="btn btn-default btn-lg" value="Valider">
		</form>
		{% if partie.finie %}
			<a class="annuler_partie" href="{% url 'leaderboard:partie_annuler' %}?id={{partie.id}}">Annuler la partie</a>
		{% else %}
			<a class="terminer_partie" href="{% url 'leaderboard:partie_terminer' %}?id={{partie.id}}">Terminer la partie</a>
		{% endif %}
	</div>
{% endblock %}

sept_tadelles/leaderboard/templates/leaderboard/partie/detail_view.html
{% extends 'leaderboard/base.html' %}


{% load static account_custom_filters %}


{% block base_headers %}
	<link rel="stylesheet" type="text/css" href="{% static 'leaderboard/css/partie/detail_change.css' %}">
{% endblock %}

{% block base_foreground %}
	<div class="foreground__heading"><h2>Partie de {{ partie.jeu }} créée à {{partie.created_at }}</h2></div>
	<div class="foreground__content">
		<div class="joueurs">
			{% for joueur in positions %}
				<p>{{ joueur.username }} : {{ positions|get_dict_value:joueur }}</p>
			{% endfor %}
		</div>
		{% if partie.finie %}
			<a class="annuler_partie" href="{% url 'leaderboard:partie_annuler' %}?id={{partie.id}}">Annuler la partie</a>
		{% else %}
			<a class="terminer_partie" href="{% url 'leaderboard:partie_terminer' %}?id={{partie.id}}">Terminer la partie</a>
		{% endif %}
	</div>
{% endblock %}

sept_tadelles/leaderboard/templates/leaderboard/partie/list.html
{% extends 'leaderboard/base.html' %}


{% load static %}


{% block base_headers %}
	<link rel="stylesheet" type="text/css" href="{% static 'leaderboard/css/partie/list.css' %}">
{% endblock %}

{% block base_foreground %}
	<div class="foreground__heading"><h2>Parties de jeu de société</h2></div>
	<div class="foreground__content">
		{% for partie in parties %}
			{% if not partie.current_month %}
				<a class="partie old" href="{% url 'leaderboard:partie_detail' %}?id={{partie.id}}">
					<div class="partie__heading"><h3>toto</h3></div>
					<div class="partie__content">
						<div class="jeu"><p>Jeu : {{partie.jeu}}</p></div>
						<div class="joueurs">
							<div class="joueurs__heading"><p>Joueurs :</p></div>
							<div class="joueurs__content">
								{% for joueur in partie.joueurs.all %}
									<p>{{ joueur }}</p>
								{% endfor %}
							</div>
						</div>
					</div>
				</a>
			{% elif partie.finie %}
				<a class="partie finie" href="{% url 'leaderboard:partie_detail' %}?id={{partie.id}}">
					<div class="partie__heading"><h3>toto</h3></div>
					<div class="partie__content">
						<div class="jeu"><p>Jeu : {{partie.jeu}}</p></div>
						<div class="joueurs">
							<div class="joueurs__heading"><p>Joueurs :</p></div>
							<div class="joueurs__content">
								{% for joueur in partie.joueurs.all %}
									<p>{{ joueur }}</p>
								{% endfor %}
							</div>
						</div>
					</div>
				</a>
			{% else %}
				<a class="partie" href="{% url 'leaderboard:partie_detail' %}?id={{partie.id}}">
					<div class="partie__heading"><h3>toto</h3></div>
					<div class="partie__content">
						<div class="jeu"><p>Jeu : {{partie.jeu}}</p></div>
						<div class="joueurs">
							<div class="joueurs__heading"><p>Joueurs :</p></div>
							<div class="joueurs__content">
								{% for joueur in partie.joueurs.all %}
									<p>{{ joueur }}</p>
								{% endfor %}
							</div>
						</div>
					</div>
				</a>
			{% endif %}
		{% endfor %}		
	</div>
{% endblock %}