sept_tadelles/account/urls.py
from django.urls import path

from .views import lieu, user, account, parameters, bot

app_name = "account"
urlpatterns = [

    path("login/", account.login_view, name="login"),
    path("logout/", account.logout_view, name="logout"),

    path("user/detail", user.detail, name="detail"),
    path("user/list", user.list, name="list"),
    path("user/add", user.add_friend, name="add_friend"),
    path("user/accept", user.accept_friend, name="accept_friend"),
    path("user/refuse", user.refuse_friend, name="refuse_friend"),
    path("user/message", user.message_friend, name="message_friend"),

    path("user/create", account.create, name="user_creation_form"),
    path("verify-email/<str:user_id>/<str:token>/", account.verify_email, name="verify_email"),

    path("password-reset-email/", account.password_reset_email_form, name="password_reset_email"),
    path("password-reset/<str:user_id>/<str:token>/", account.password_reset_form, name="password_reset"),

    path("discord-verification-send-email/<str:discord_name>/<str:discord_id>/<str:user_name>/<str:bot_token>", account.discord_verification_send_email, name="discord_verification_send_email"),
    path("discord-verification-link/<str:user_id>/<str:token>", account.discord_verification_link, name="discord_verification_link"),

    path("parameters", parameters.base, name="parameters_base"),
    path("parameters/profile", parameters.profile, name="parameters_profile"),
    path("parameters/address", parameters.address, name="parameters_address"),
    path("parameters/address/delete", parameters.delete_address, name="parameters_delete_address"),
    path("parameters/type-soiree", parameters.type_soiree, name="parameters_type_soiree"),
    path("parameters/notif-mail", parameters.notif_mail, name="parameters_notif_mail"),
    path("parameters/delete-profile-photo", parameters.delete_profile_photo, name="delete_profile_photo"),
    path("parameters/delete-cover-photo", parameters.delete_cover_photo, name="delete_cover_photo"),



    path("bot/get-ranking-games/<str:bot_token>", bot.get_ranking_games, name="get_ranking_games"),
    path("bot/get-classement/<str:bot_token>", bot.get_classement, name="get_classement"),
    path("bot/get-score/<str:bot_token>", bot.get_score, name="get_score"),
    path("bot/month-end-validation/<str:bot_token>", bot.month_end_validation, name="month_end_validation"),



    # ajouter jeu
    path("game/add", account.add_game, name="add_game"),

    # Lieu
    path("place/add", lieu.create_lieu, name="create_lieu"),

    path("clean-session", account.clean_session, name="clean_session"),
    path("retour1", account.retour1, name="retour1"),
    path("retour2", account.retour2, name="retour2"),
]

sept_tadelles/sept_tadelles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('welcome.urls')),
    path('wiki/', include('wiki.urls')),
    path('account/', include('account.urls')),
    path('soiree/', include('soiree.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sept_tadelles/welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.index, name="index"),
]

sept_tadelles/wiki/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:game_id>/", views.detail, name="detail"),
]

sept_tadelles/wiki/models.py
from django.db import models
import unidecode

from django.conf import settings



def image_name(instance, filename) :
	return f"wiki/games/{instance.short_name}/{instance.short_name}.png" 

def bg_image_name(instance, filename) :
	return f"wiki/games/{instance.short_name}/bg_{instance.short_name}.png" 

def rules_pdf_name(instance, filename) :
	return f"wiki/games/{instance.short_name}/{instance.short_name}.pdf" 



class Category(models.Model) :

	name = models.CharField(max_length=50)
	short_name = models.CharField(max_length=50)

	def __str__(self) :
		return self.name

class Game(models.Model) :

	name = models.CharField(max_length=50)
	short_name = models.CharField(max_length=50)

	has_image = models.BooleanField(default=False)
	image = models.ImageField(
		verbose_name = "Image",
		upload_to = image_name,
		null = True,
		blank = True
	)

	has_bg_image = models.BooleanField(default=False)
	bg_image = models.ImageField(
		verbose_name = "Background image",
		upload_to = bg_image_name,
		null = True,
		blank = True
	)

	bg_color = models.CharField(
		verbose_name = "Background color",
		max_length = 7,
		null = True,
		blank = True
	)

	players_min = models.IntegerField(default=0)
	players_max = models.IntegerField(default=0)
	duration = models.CharField(max_length=20, default="")
	age_min = models.IntegerField(default=0)

	description = models.TextField(default="")

	video_url = models.CharField(max_length=200, default="")

	#downloads_txt = models.CharField(max_length=200, default="")

	has_rules_pdf = models.BooleanField(default=False)
	rules_pdf = models.FileField(
		verbose_name = "PDF rules",
		upload_to=rules_pdf_name,
		null=True,
		blank=True
	)

	category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

	ranking = models.BooleanField(default=False)

	def __init__(self, *args, **kwargs) :
		super(Game, self).__init__(*args, **kwargs)
		self.short_name = unidecode.unidecode(self.name.replace(" ", "_").lower())
		#self.has_image = self.image != None
		#self.has_bg_image = self.bg_image != None
		#self.has_rules_pdf = self.rules_pdf != None

	def save(self, *args, **kwargs) :
		self.short_name = unidecode.unidecode(self.name.replace(" ", "_").lower())
		#self.has_image = self.image != None
		#self.has_bg_image = self.bg_image != None
		#self.has_rules_pdf = self.rules_pdf != None
		super(Game, self).save(*args, **kwargs)

	def __str__(self) :
		return self.name

sept_tadelles/wiki/forms.py
from django import forms
from django.core.validators import MinValueValidator

from . import models

class GameForm(forms.Form) :

	name = forms.CharField(
		label = "Name",
		max_length = 50
	)

	image = forms.ImageField(
		label = "Image",
		required = False
	)

	bg_image = forms.ImageField(
		label = "Background image",
		required = False
	)

	bg_color = forms.CharField(
		label = "Background color",
		required = False
	)

	players_min = forms.IntegerField(
		label = "Players min",
		validators = [MinValueValidator(1)],
		min_value = 1
	)

	players_max = forms.IntegerField(
		label = "Players max",
	)

	duration = forms.CharField(
		label = "Game duration",
		max_length = 15,
	)

	age_min = forms.IntegerField(
		label = "Minimum age",
		validators = [MinValueValidator(0)],
		min_value = 0
	)

	description = forms.CharField(
		label = "Description",
		max_length = 1000,
		widget = forms.Textarea()
	)

	video_url = forms.CharField(
		label = "Youtube vidéo ID",
		max_length = 15,
		initial = "none"
	)

	rules_pdf = forms.FileField(
		label = "Rules PDF",
		required = False
	)

	category = forms.ModelChoiceField(
		label = "Category",
		queryset = models.Category.objects.all()
	)

sept_tadelles/wiki/views.py
from django.contrib import admin as django_admin
from django.shortcuts import render, redirect
from django.http import HttpResponse

from account.views import helpers

from . import models, admin

def index(request):

    current_view = ['wiki:index', []]

    games = models.Game.objects.all()

    helpers.register_view(request, current_view)
    return render(request, "wiki/index.html", {
        "games": games,
        "categories": models.Category.objects.all(),
    })

def detail(request, game_id) :

    current_view = ['wiki:detail', []]

    try :
        game = models.Game.objects.get(pk=game_id)
    except :
        game = None

    if admin.GameAdmin(models.Game, django_admin.site).has_view_permission(request, game) :
        helpers.register_view(request, current_view)
        return render(request, 'wiki/detail.html', {'game': game})
    else :
        return render(request, 'account/error.html', {'error_txt': "Vous n'avez pas la permission de voir ce jeu (ou alors aucun jeu n'a cet identifiant)."})

sept_tadelles/wiki/templates/wiki/base.html
<!DOCTYPE html>

{% load static %}

<html>
	<head>
		<title>7tadelles</title>
		<link rel="icon" href="{% static 'welcome/7tadelles_icon.png' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'wiki/css/base.css' %}">
		{% block extra_headers %}{% endblock %}
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
	</head>
	<body>

		<div class="background">
			{% block background %}{% endblock %}
		</div>

		<a href="{% url 'account:retour2' %}" class="btn btn-retour">
			<img src="{% static 'wiki/photos/nuage.png' %}">
			<p>retour</p>
		</a>

		<div class="foreground">
			{% block foreground %}{% endblock %}
		</div>

	</body>
</html>

sept_tadelles/wiki/templates/wiki/detail.html
{% extends 'wiki/base.html' %}


{% load static custom_filters %}


{% block extra_headers %}
<link rel="stylesheet" type="text/css" href="{% static 'wiki/css/detail.css' %}">
<script src="https://www.youtube.com/iframe_api"></script>
{% endblock %}

{% block btn_retour %}
	<a href="{% url 'wiki:index' %}" class="btn btn-retour">
		<img src="{% static 'wiki/photos/nuage.png' %}">
		<p>retour</p>
	</a>
{% endblock %}

{% block foreground %}
<style type="text/css">
	{% if game.has_bg_image %}
		body {
			background: #333 ;
		}
		.background::before {
			content: "";

			position: absolute;
			width: 100%;
			aspect-ratio: 1 / 1;
			top: 49vh;

			background: url("{{ game.bg_image.url }}") top center;
			background-size: cover;

			transform: translateZ(-1px) scale(2);

			box-shadow: 0 -400px 500px -100px #333 inset;

			z-index: 2;
		}
	{% else %}
		body {
			background: #fff ;
		}
		.background::before {
			content: "";
			width: 100vw;
			height: 300%;
			position: absolute;

			background: url("{% static 'wiki/photos/default_background.jpg' %}") top center;
			background-size: 40%;
			background-repeat: repeat;

			box-shadow: 0 -50vh 100px -150px #fff inset;

			transform: translateZ(-1px) scale(2);
		}
	{% endif %}
</style>

	<div class="foreground__heading"><h1>{{ game.name }}</h1></div>
	<div class="foreground__content">
		<div class="block preview">
			<div class="block-heading preview__heading"><h2>Présentation générale</h2></div>
			<div class="block-content preview__content">
				<div class="preview__fig">
					<div class="preview__imgwrapper">
						{% if game.has_image %}
							<img src="{{ game.image.url }}">
						{% else %}
							<img src="{% static 'wiki/photos/default_game_image.png' %}">
						{% endif %}
					</div>
				</div>
				<div class="preview__txt">
					<div class="preview__players">
						<img class="preview__txtimg" src="{% static 'wiki/photos/boardgame_players.png' %}">
						<p>{{game.players_min}} - {{game.players_max}} joueurs</p>
					</div>
					<div class="preview__age">
						<img class="preview__txtimg" src="{% static 'wiki/photos/boardgame_age.png' %}" />
						<p>{{game.age_min}}+</p>
					</div>
					<div class="preview__duration">
						<img class="preview__txtimg" src="{% static 'wiki/photos/boardgame_duration.png' %}" />
						<p>{{game.duration}}</p>
					</div>
				</div>
			</div>
		</div>
		<div class="block description">
			<div class="block-heading description__heading"><h2>Description</h2></div>
			<div class="block-content description__content">
				<p>{{game.description|linebreaks}}</p>
			</div>
		</div>
		<div class="block video">
			<div class="block-heading video__heading"><h2>Les règles en vidéo</h2></div>
			<div class="block-content video__content">
				{% if game.video_url != "none" %}
					<div class="video__player">
						<div id="player">
							<script>
							    // Fonction d'initialisation appelée lorsque l'API JavaScript de YouTube est prête
							    function onYouTubeIframeAPIReady() {
							        // Créez un lecteur vidéo YouTube
							        var player = new YT.Player('player', {
							            videoId: '{{game.video_url}}',
							            width: 560*1.5,
							            height: 315*1.5,
							            playerVars: {
							                // Options supplémentaires (facultatives)
							            }
							        });
							    }
							</script>
						</div>
					</div>
				{% else %}
					<div class="no-video">(oups, pas de vidéo de Ludochrono sur {{game.name}} malheureusement)</div>	
				{% endif %}
			</div>
		</div>
		<div class="block regles">
			<div class="block-heading regles__heading"><h2>Télécharger les règles</h2></div>
			<div class="block-content regles__content">
				{% if game.has_rules_pdf %}
					<a class="btn btn--round btn--big" href="{{ game.rules_pdf.url }}" target="_blank" download="{{ game.short_name }}-rules.pdf"><div>Règles</div></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

{% block left_sidebar %}
	{% for action in left_actions %}
		{% if action.2 %}
			{% with action_args=action.2 %}
				<div class="action"><a href="{% url action.1 action_args %}"><p>{{ action.0 }}</p></a></div>
			{% endwith %}
		{% else %}
			<div class="action"><a href="{% url action.1 %}"><p>{{ action.0 }}</p></a></div>
		{% endif %}
	{% endfor %}
{% endblock %}



{% block right_sidebar %}
	{% for action in right_actions %}
		{% if action.2 %}
			{% with action_args=action.2 %}
				<div class="action"><a href="{% url action.1 action_args %}"><p>{{ action.0 }}</p></a></div>
			{% endwith %}
		{% else %}
			<div class="action"><a href="{% url action.1 %}"><p>{{ action.0 }}</p></a></div>
		{% endif %}
	{% endfor %}
{% endblock %}

sept_tadelles/wiki/templates/wiki/index.html
{% extends 'wiki/base.html' %}


{% load static %}


{% block extra_headers %}
	<link rel="stylesheet" type="text/css" href="{% static 'wiki/css/index.css' %}">
{% endblock %}

{% block btn_retour %}
	<a href="{% url 'welcome:index' %}" class="btn btn-retour">
		<img src="{% static 'wiki/photos/nuage.png' %}">
		<p>retour</p>
	</a>
{% endblock %}






{% block background %}
	<div class="background__txt">WIKI</div>
{% endblock %}


{% block foreground %}
	<div class="foreground__heading"><h1>Jeux de société</h1></div>
	<div class="foreground__content">
		{% for game in games %}
			<a class="game" href="{% url 'wiki:detail' game.id %}">
				<div class="game__fig">
					<div class="game__imgwrapper">
						{% if game.has_image %}
							<img src="{{ game.image.url }}">
						{% else %}
							<img src="{% static 'wiki/photos/default_game_image.png' %}">
						{% endif %}
					</div>
				</div>
				<div class="game__txt"><p>{{game.name}}</p></div>
			</a>
		{% endfor %}
	</div>
	
{% endblock %}