sept_tadelles/account/urls.py
from django.urls import path

from .views import lieu, user, account, parameters, bot

app_name = "account"
urlpatterns = [

    path("login/", account.login_view, name="login"),
    path("logout/", account.logout_view, name="logout"),

    path("user/detail", user.detail, name="detail"),
    path("user/list", user.list, name="list"),
    path("user/add", user.add_friend, name="add_friend"),
    path("user/accept", user.accept_friend, name="accept_friend"),
    path("user/refuse", user.refuse_friend, name="refuse_friend"),
    path("user/message", user.message_friend, name="message_friend"),

    path("user/create", account.create, name="user_creation_form"),
    path("verify-email/<str:user_id>/<str:token>/", account.verify_email, name="verify_email"),

    path("password-reset-email/", account.password_reset_email_form, name="password_reset_email"),
    path("password-reset/<str:user_id>/<str:token>/", account.password_reset_form, name="password_reset"),

    path("discord-verification-send-email/<str:discord_name>/<str:discord_id>/<str:user_name>/<str:bot_token>", account.discord_verification_send_email, name="discord_verification_send_email"),
    path("discord-verification-link/<str:user_id>/<str:token>", account.discord_verification_link, name="discord_verification_link"),

    path("parameters", parameters.base, name="parameters_base"),
    path("parameters/profile", parameters.profile, name="parameters_profile"),
    path("parameters/address", parameters.address, name="parameters_address"),
    path("parameters/address/delete", parameters.delete_address, name="parameters_delete_address"),
    path("parameters/type-soiree", parameters.type_soiree, name="parameters_type_soiree"),
    path("parameters/notif-mail", parameters.notif_mail, name="parameters_notif_mail"),
    path("parameters/delete-profile-photo", parameters.delete_profile_photo, name="delete_profile_photo"),
    path("parameters/delete-cover-photo", parameters.delete_cover_photo, name="delete_cover_photo"),



    path("bot/get-ranking-games/<str:bot_token>", bot.get_ranking_games, name="get_ranking_games"),
    path("bot/get-classement/<str:bot_token>", bot.get_classement, name="get_classement"),
    path("bot/get-score/<str:bot_token>", bot.get_score, name="get_score"),
    path("bot/month-end-validation/<str:bot_token>", bot.month_end_validation, name="month_end_validation"),



    # ajouter jeu
    path("game/add", account.add_game, name="add_game"),

    # Lieu
    path("place/add", lieu.create_lieu, name="create_lieu"),

    path("clean-session", account.clean_session, name="clean_session"),
    path("retour1", account.retour1, name="retour1"),
    path("retour2", account.retour2, name="retour2"),
]

sept_tadelles/sept_tadelles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('welcome.urls')),
    path('wiki/', include('wiki.urls')),
    path('account/', include('account.urls')),
    path('soiree/', include('soiree.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sept_tadelles/soiree/urls.py
from django.urls import path

from . import views

app_name = "soiree"
urlpatterns = [
    path("list", views.list, name="list"),
    path("detail", views.detail, name="detail"),
    path("creation-1", views.creation_step_1, name="creation_step_1"),
    path("creation-2", views.creation_step_2, name="creation_step_2"),
    path("creation-3", views.creation_step_3, name="creation_step_3"),
    path("creation-4", views.creation_step_4, name="creation_step_4"),
    path("invites", views.change_invites, name="change_invites"),
    path("inscription", views.inscription, name="inscription"),
    path("desinscription", views.desinscription, name="desinscription"),
    path("delete", views.delete_soiree, name="delete_soiree"),
]

sept_tadelles/wiki/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:game_id>/", views.detail, name="detail"),
]

sept_tadelles/account/forms/soiree.py
from django import forms
from django.core.validators import MinValueValidator

from account import models




class SoireeCreationForm_step_1(forms.Form) :

	type_soiree = forms.ChoiceField(
		label = "Type de soirée",
		choices = models.Soiree.TypeDeSoiree.choices,
		widget = forms.RadioSelect()
	)

class SoireeCreationForm_step_2(forms.Form) :

	nb_joueurs = forms.IntegerField(
		label = "Nombre maximal de joueurs (hôte compris)",
		validators = [MinValueValidator(2)],
		min_value = 2
	)

class SoireeCreationForm_step_3(forms.Form) :

	lieu = forms.ModelChoiceField(label="Lieu", queryset=models.Lieu.objects.all())

	def __init__(self, request, *args, **kwargs) :
		super(SoireeCreationForm_step_3, self).__init__(*args, **kwargs)
		self.fields['lieu'].queryset = request.user.lieus.all()

class SoireeCreationForm_step_4(forms.Form) :

	date = forms.DateTimeField(label="Date", widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

class InvitesForm(forms.Form) :
	filter_horizontal = ('invites_to_add',)

	invites_to_add = forms.ModelMultipleChoiceField(
		label="Joueur(s) à inviter",
		queryset=None,
		required=False
	)

	def __init__(self, request, soiree, *args, **kwargs) :
		super(InvitesForm, self).__init__(*args, **kwargs)
		invites_to_add_queryset = request.user.amis.all()
		for invite in soiree.invites.all() :
			invites_to_add_queryset = invites_to_add_queryset.exclude(pk=invite.id)

		self.fields['invites_to_add'].queryset = invites_to_add_queryset


class SoireeForm(forms.Form) :

	type_soiree = forms.ChoiceField(
		label = "Type de soirée",
		choices = models.Soiree.TypeDeSoiree.choices,
		widget = forms.RadioSelect()
	)

	nb_joueurs = forms.IntegerField(
		label = "Nombre maximal de joueurs (hôte compris)",
		validators = [MinValueValidator(2)],
		min_value = 2
	)

	lieu = forms.ModelChoiceField(
		label="Lieu",
		queryset=models.Lieu.objects.all()
	)

	date = forms.DateTimeField(
		label="Date",
		widget=forms.DateTimeInput(attrs={'type': 'datetime-local'})
	)

	def __init__(self, request, soiree, *args, **kwargs) :
		super(SoireeForm, self).__init__(*args, **kwargs)
		self.fields['type_soiree'].initial = soiree.type_soiree
		self.fields['nb_joueurs'].initial = soiree.nb_joueurs
		self.fields['lieu'].initial = soiree.lieu
		self.fields['date'].initial = soiree.date

		self.fields['lieu'].queryset = request.user.lieus.all()

sept_tadelles/soiree/views.py
from django.contrib import admin as django_admin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone

import datetime as dt

from account import models as account_models
from account import admin as account_admin
from account import forms as account_forms
from account.views import helpers

from . import models, forms, admin

@login_required
def list(request) :

	filtre = request.GET.get('filter', 'all') # hote, invitations, inscriptions, all
	type_soiree = int(request.GET.get('type', request.user.parameters['type_soiree_view']))

	current_view = [f"{reverse('soiree:list')}?filter={filtre}&type={type_soiree}", []]

	if filtre == "all" :
		filtre = "hote+inscriptions+invitations"

	TYPES_SOIREE = [
		models.Soiree.TypeDeSoiree.PUB,
		models.Soiree.TypeDeSoiree.PUB_INSC,
		models.Soiree.TypeDeSoiree.PRIV_LIST_INSC,
		models.Soiree.TypeDeSoiree.PRIV_INVIT_CONFIRM,
	]

	all_soirees = models.Soiree.objects.none()
	for i,elt in enumerate(TYPES_SOIREE) :
		if (type_soiree//(2**i))%2 == 1 :
			all_soirees = all_soirees.union(models.Soiree.objects.filter(type_soiree__exact=TYPES_SOIREE[i]))

	mes_soirees = models.Soiree.objects.none()
	inscriptions = models.Soiree.objects.none()
	invitations = models.Soiree.objects.none()
	if "hote" in filtre :
		mes_soirees = all_soirees.intersection(request.user.soirees_hote.all())
	if "inscriptions" in filtre :
		inscriptions = all_soirees.intersection(request.user.user_inscriptions.all())
	if "invitations" in filtre :
		invitations = all_soirees.intersection(request.user.invitations.difference(request.user.user_inscriptions.all()))

	helpers.register_view(request, current_view)
	return render(request, 'soiree/soiree/list.html', {
		'mes_soirees': mes_soirees,
		'inscriptions': inscriptions,
		'invitations': invitations,
	})

@login_required
def detail(request) :

	soiree_id = request.GET.get("id", False)

	current_view = [f"{reverse('soiree:detail')}{f'?id={soiree_id}' if soiree_id else ''}", []]

	if soiree_id :
		
		try :
			soiree = models.Soiree.objects.get(pk=soiree_id)
		except :
			soiree = None

		if admin.SoireeAdmin(models.Soiree, django_admin.site).has_change_permission(request, soiree) :

			form = forms.SoireeForm(request, soiree)
			errors = {
				'errors_count': 0,
				'not_enough_places': [False, "Il ne peut pas y avoir moins de places que d'invités pour une soirée privée avec liste d'invités. Retirez des invités avant de réduire le nombre de places."],
				'passed_date': [False, "Vous ne pouvez pas renseigner une date passée"],
			}
			if request.method == "POST" :
				form = forms.SoireeForm(request, soiree, request.POST)
				if form.is_valid() :
					if soiree.type_soiree == models.Soiree.TypeDeSoiree.PRIV_INVIT_CONFIRM and form.cleaned_data['nb_joueurs'] < len(soiree.invites.all())+1 :
						errors['not_enough_places'][0] = True
						errors['errors_count'] += 1
					if form.cleaned_data['date'] < timezone.now() :
						errors['passed_date'][0] = True
						errors['errors_count'] += 1
					if errors['errors_count'] == 0 :
						soiree.type_soiree = form.cleaned_data['type_soiree']
						soiree.nb_joueurs = form.cleaned_data['nb_joueurs']
						soiree.lieu = form.cleaned_data['lieu']
						soiree.date = form.cleaned_data['date']
						soiree.save()
			errors.pop('errors_count')
			helpers.register_view(request, current_view)
			return render(request, 'soiree/soiree/detail_change.html', {
				'form': form,
				'errors': errors,
				'soiree': soiree,
				'types_soiree': models.Soiree.TypeDeSoiree.choices,
				'types_soiree_desc': models.Soiree.TYPES_SOIREE_DESC,
			})

		if admin.SoireeAdmin(models.Soiree, django_admin.site).has_view_permission(request, soiree) :

			helpers.register_view(request, current_view)
			return render(request, 'soiree/soiree/detail_view.html', {
				'soiree': soiree,
				'types_soiree': models.Soiree.TypeDeSoiree.choices,
				'types_soiree_desc': models.Soiree.TYPES_SOIREE_DESC,
			})

		else :

			return render(request, 'soiree/error.html', {"error_txt": "Vous n'avez pas la permission de voir ou de modifier cette soirée"})

	else :

		return redirect('account:retour1')



@login_required
def creation_step_1(request) :

	current_view = ['soiree:creation_step_1', []]

	if admin.SoireeAdmin(models.Soiree, django_admin.site).has_add_permission(request) :

		form = forms.CreationForm_step_1(request)
		if request.method == "POST" :
			form = forms.CreationForm_step_1(request, request.POST)
			if form.is_valid() :
				soiree = models.Soiree(
					type_soiree = form.cleaned_data['type_soiree'],
					nb_joueurs = models.Soiree()._meta.get_field('nb_joueurs').default,
					lieu = request.user.adresse,
					date = dt.datetime.now() + dt.timedelta(days=1),
					hote = request.user,
					has_image = False,
					image = None,
					created_at = dt.datetime.now(),
				)
				soiree.save()
				if form.cleaned_data['type_soiree'] in [models.Soiree.TypeDeSoiree.PUB_INSC, models.Soiree.TypeDeSoiree.PUB] :
					for user in account_models.User.objects.exclude(pk=request.user.id) :
						soiree.invites.add(user)
				soiree.save()
				return redirect(f"{reverse('soiree:creation_step_2')}?id={soiree.id}")
		#helpers.register_view(request, current_view)
		return render(request, 'soiree/soiree/creation_step_1.html', {'form': form})

	else :

		return render(request, 'soiree/error.html', {'error_txt': "Vous n'avez pas la permission de créer une nouvelle soirée"})

@login_required
def creation_step_2(request) :

	soiree_id = request.GET.get('id', False)

	current_view = [f"{reverse('soiree:creation_step_2')}{f'?id={soiree_id}' if soiree_id else ''}", []]

	if soiree_id :

		try :
			soiree = models.Soiree.objects.get(pk=soiree_id)
		except :
			soiree = None

		if admin.SoireeAdmin(models.Soiree, django_admin.site).has_change_permission(request, soiree) :

			form = forms.CreationForm_step_2(request)
			if request.method == "POST" :
				form = forms.CreationForm_step_2(request, request.POST)
				if form.is_valid() :
					soiree.nb_joueurs = form.cleaned_data['nb_joueurs']
					soiree.save()
					return redirect(f"{reverse('soiree:creation_step_3')}?id={soiree.id}")
			#helpers.register_view(request, current_view)
			return render(request, 'soiree/soiree/creation_step_2.html', {'form': form})

		else :
			return render(request, 'soiree/error.html', {'error_txt': "Vous n'avez pas la permission de modifier cette soirée"})

	else :
		
		return redirect('account:retour1')

@login_required
def creation_step_3(request) :

	soiree_id = request.GET.get('id', False)

	current_view = [f"{reverse('soiree:creation_step_3')}{f'?id={soiree_id}' if soiree_id else ''}", []]

	if soiree_id :

		try :
			soiree = models.Soiree.objects.get(pk=soiree_id)
		except :
			soiree = None

		if admin.SoireeAdmin(models.Soiree, django_admin.site).has_change_permission(request, soiree) :

			form = forms.CreationForm_step_3(request)
			if request.method == "POST" :
				form = forms.CreationForm_step_3(request, request.POST)
				if form.is_valid() :
					soiree.lieu = form.cleaned_data['lieu']
					soiree.save()
					return redirect(f"{reverse('soiree:creation_step_4')}?id={soiree.id}")
			helpers.register_view(request, current_view)
			return render(request, 'soiree/soiree/creation_step_3.html', {'form': form})

		else :
			return render(request, 'soiree/error.html', {'error_txt': "Vous n'avez pas la permission de modifier cette soirée"})

	else :
		
		return redirect('account:retour1')

@login_required
def creation_step_4(request) :

	soiree_id = request.GET.get('id', False)

	current_view = [f"{reverse('soiree:creation_step_4')}{f'?id={soiree_id}' if soiree_id else ''}", []]

	if soiree_id :

		try :
			soiree = models.Soiree.objects.get(pk=soiree_id)
		except :
			soiree = None

		if admin.SoireeAdmin(models.Soiree, django_admin.site).has_change_permission(request, soiree) :

			form = forms.CreationForm_step_4(request)
			errors = {
				'errors_count': 0,
				'passed_date': [False, "Vous ne pouvez pas renseigner une date passée"]
			}
			if request.method == "POST" :
				form = forms.CreationForm_step_4(request, request.POST)
				if form.is_valid() :
					if form.cleaned_data['date'] < timezone.now() :
						errors['passed_date'][0] = True
						errors['errors_count'] += 1
					if errors['errors_count'] == 0 :
						soiree.date = form.cleaned_data['date']
						soiree.save()
						return render(request, 'soiree/soiree/creation_success.html', {})
			errors.pop('errors_count')
			#helpers.register_view(request, current_view)
			return render(request, 'soiree/soiree/creation_step_4.html', {'form': form, 'errors': errors})

		else :
			return render(request, 'soiree/error.html', {'error_txt': "Vous n'avez pas la permission de modifier cette soirée"})

	else :
		
		return redirect('account:retour1')

@login_required
def change_invites(request) :

	soiree_id = request.GET.get('id', False)

	current_view = [f"{reverse('soiree:change_invites')}{f'?id={soiree_id}' if soiree_id else ''}", []]

	if soiree_id :

		try :
			soiree = models.Soiree.objects.get(pk=soiree_id)
		except :
			soiree = None

		if admin.SoireeAdmin(models.Soiree, django_admin.site).has_change_permission(request, soiree) :

			form = forms.InvitesForm(request, soiree)
			errors = {
				'errors_count': 0,
				'too_many_guests': [False, "Vous ne pouvez pas inviter autant de monde"],
			}
			if request.method == "POST" :
				form = forms.InvitesForm(request, soiree, request.POST)
				if form.is_valid() :
					if soiree.type_soiree == models.Soiree.TypeDeSoiree.PRIV_INVIT_CONFIRM :
						nb_joueurs = len(soiree.invites.all())+1 + len(form.cleaned_data['invites_to_add'])
						if nb_joueurs > soiree.nb_joueurs :
							errors['too_many_guests'][0] = True
							errors['errors_count'] += 1
					if errors['errors_count'] == 0 :
						notification = account_models.Notification(

sept_tadelles/soiree/templates/soiree/soiree/creation_step_3.html
{% extends 'soiree/base_form.html' %}

{% block extra_headers %}
<style type="text/css">
	.pre-text {
		font-size: 1.8vw;
	}
	input {
		font-size: 1.5vw;
	}
</style>
{% endblock %}

{% block title %}
	<h1>Où se déroulera cette soirée ?</h1>
{% endblock %}

{% block pre-text %}
	<form action="" method="post">
		{% csrf_token %}
		<p>Veuillez indiquer l'endroit où se déroulera la soirée jeux : {{ form.lieu }}</p>
		<p><a href="{% url 'account:create_lieu' %}">créer un nouveau lieu</a></p>
		<input type="submit" class="btn btn-default btn-lg" value="Suivant">
	</form>
{% endblock %}

{% block errors %}
	{% for error_name, value in errors.items %}
		{% if value.0 %}
			<p>{{ value.1 }}</p>
		{% endif %}
	{% endfor %}
{% endblock %}

{% block form %}

{% endblock %}

sept_tadelles/soiree/templates/soiree/soiree/creation_success.html
{% extends 'soiree/base_form.html' %}

{% block title %}
	<h1>Soirée créée avec succès</h1>
{% endblock %}

{% block pre-text %}
	<p>
		La soirée a été créée avec succes, vous pouvez voir le détail de celle-ci depuis votre espace utilisateur.
	</p>
	<p><a href="{% url 'account:retour2' %}">retour</a></p>
{% endblock %}

sept_tadelles/soiree/templates/soiree/soiree/detail_change.html
{% extends 'soiree/base.html' %}


{% load static account_custom_filters %}


{% block extra_headers %}
	<link rel="stylesheet" type="text/css" href="{% static 'soiree/css/detail.css' %}">
{% endblock %}

{% block btn_retour %}
	<a href="{% url 'account:retour2' %}" class="btn btn-retour">
		<img src="{% static 'wiki/photos/nuage.png' %}">
		<p>retour</p>
	</a>
{% endblock %}

{% block foreground %}
	<div class="heading foreground__heading">
		<h1>Soirée du {{ soiree.date.day }}/{{ soiree.date.month }}/{{ soiree.date.year }}</h1>
	</div>
	<div class="errors">
		{% for error_name, value in errors.items %}
			{% if value.0 %}
				<p>{{ value.1 }}</p>
			{% endif %}
		{% endfor %}
	</div>
	<form class="content foreground__content" action="" method="post">
		{% csrf_token %}
		<div class="colums-block">
			<div class="column column-left">
				<div class="block type_soiree">
					<div class="heading block-heading col-block-heading type_soiree__heading"><h2>Type de Soirée :</h2></div>
					<div class="content block-content col-block-content type_soiree__content">
						<p>
							{{ form.type_soiree }}
						</p>
						<p>
							{% for type_soiree in types_soiree %}
								{% if soiree.type_soiree == type_soiree.0 %}
									{{ types_soiree_desc|get_dict_value:type_soiree.0 }}
								{% endif %}
							{% endfor %}
						</p>
					</div>
				</div>
				<div class="block nb_joueurs">
					<div class="heading block-heading col-block-heading nb_joueurs__heading"><h2>Nombre de places :</h2></div>
					<div class="content block-content col-block-content nb_joueurs__content">
						<p>Il y aura au maximum {{ form.nb_joueurs }} joueurs à cette soirée.</p>
					</div>
				</div>
				<div class="block hote">
					<div class="heading block-heading col-block-heading hote__heading"><h2>Hôte de la soirée :</h2></div>
					<div class="content block-content col-block-content hote__content">
						<div class="hote__detail">
							<div class="hote__fig">
								<div class="hote__imgwrapper">
									{% if soiree.hote.has_profile_photo %}
										<img src="{{ soiree.hote.profile_photo.url }}">
									{% else %}
										<img src="{% static 'account/default_profile_photo.jpg' %}">
									{% endif %}
								</div>
							</div>
							<div class="hote__txt">
								<p>{{ soiree.hote.username }}</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="column colum-right">
				<div class="block lieu">
					<div class="heading block-heading col-block-heading lieu__heading"><h2>Lieu de la soirée :</h2></div>
					<div class="content block-content col-block-content lieu__content">
						<p>{{ soiree.lieu.name }} :</p>
						<div class="lieu__imgwrapper">
							{% if soiree.lieu.has_image %}
								<img src="{{ soiree.lieu.image.url }}">
							{% else %}
								<img src="{% static 'account/photos/lieu/default_image.jpg' %}">
							{% endif %}
						</div>
						<p>{{ soiree.lieu.adresse }}</p>
						<p>{{ soiree.lieu.code_postal}}, {{ soiree.lieu.ville }}</p>
						<p>Modifier le lieu : {{ form.lieu }}</p>
					</div>
				</div>
				<div class="block date">
					<div class="heading block-heading col-block-heading date__heading"><h2>Date de la soirée :</h2></div>
					<div class="content block-content col-block-content date__content">
						<p>
							{{ soiree.date|week_day }} {{ soiree.date.day }} {{ soiree.date|month_str }} {{ soiree.date.year }}, à {{ soiree.date.hour }}h{{ soiree.date.minute }}
						</p>
						<p>Modifier : {{ form.date }}</p>
					</div>	
				</div>
			</div>
		</div>
		<div class="block invites">
			<div class="heading block-heading nocol-block-heading invites__heading"><h2>Joueurs invités à la soirée :</h2></div>
			<div class="content block-content nocol-block-content invites__content">
				{% for invite in soiree.invites.all %}
					<div class="invite__detail">
						<div class="invite__fig">
							<div class="invite__imgwrapper">
								{% if invite.has_profile_photo %}
									<img src="{{ invite.profile_photo.url }}">
								{% else %}
									<img src="{% static 'account/photos/user/default_profile_photo.jpg' %}">
								{% endif %}
							</div>
						</div>
						<div class="invite__txt">
							<p>{{ invite.username }}</p>
						</div>					
					</div>
				{% endfor %}
				<a class="invites__add" href="{% url 'soiree:change_invites' %}?id={{soiree.id}}"><img src="{% static 'soiree/images/add_invites.png' %}"></a>	
			</div>
		</div>
		<div class="buttons">
			<input type="submit" class="enregistrer" value="Enregistrer">
			<a href="{% url 'soiree:delete_soiree' %}?id={{soiree.id}}" class="supprimer">Supprimer</a>
		</div>
		<div class="block discussion">
			<div class="heading block-heading nocol-block-heading discussion__heading"><h2>Discussion :</h2></div>
			<div class="content block-content nocol-block-content discussion__content">
				<p>(prochainement)</p>
			</div>
		</div>
	</form>
{% endblock %}

sept_tadelles/soiree/templates/soiree/soiree/list.html
{% extends 'soiree/base.html' %}


{% load static account_custom_filters %}


{% block extra_headers %}
	<link rel="stylesheet" type="text/css" href="{% static 'soiree/css/list.css' %}">
{% endblock %}

{% block btn_retour %}
	<a href="{% url 'account:retour2' %}" class="btn btn-retour">
		<img src="{% static 'wiki/photos/nuage.png' %}">
		<p>retour</p>
	</a>
{% endblock %}

{% block foreground %}
	<div class="foreground__heading"><h1>Les soirées ...</h1></div>
	<div class="foreground__content">

		{% if mes_soirees %}
			<div class="soirees__heading"><h2>... dont je suis l'hôte</h2></div>
			<div class="soirees__content">
				{% for soiree in mes_soirees %}
					<a class="soiree" href="{% url 'soiree:detail' %}?id={{soiree.id}}">
						<div class="soiree__heading">
							<h2>{{ soiree.date|week_day }} {{ soiree.date.day }} {{ soiree.date|month_str }} {{ soiree.date.year }}</h2>
						</div>
						<div class="soiree__content">
							<div class="soiree__fig">
								<div class="soiree__imgwrapper">
									{% if soiree.has_image %}
										<img src="{{ soiree.image.url }}">
									{% else %}
										<img src="{% static 'soiree/images/default_image.jpg' %}">
									{% endif %}
								</div>
							</div>
							<div class="soiree__txt">
								<p class="lieu">{{ soiree.lieu.name }}</p>
							</div>						
						</div>
					</a>
				{% endfor %}
			</div>
		{% endif %}

		{% if inscriptions %}
			<div class="soirees__heading"><h2>... auxquelles je suis inscrit(e)</h2></div>
			<div class="soirees__content">
				{% for soiree in inscriptions %}
					<a class="soiree" href="{% url 'soiree:detail' %}?id={{soiree.id}}">
						<div class="soiree__heading">
							<h2>{{ soiree.date|week_day }} {{ soiree.date.day }} {{ soiree.date|month_str }} {{ soiree.date.year }}</h2>
						</div>
						<div class="soiree__content">
							<div class="soiree__fig">
								<div class="soiree__imgwrapper">
									{% if soiree.has_image %}
										<img src="{{ soiree.image.url }}">
									{% else %}
										<img src="{% static 'soiree/images/default_image.jpg' %}">
									{% endif %}
								</div>
							</div>
							<div class="soiree__txt">
								<p class="lieu">{{ soiree.lieu.name }}</p>
							</div>						
						</div>
					</a>
				{% endfor %}
			</div>
		{% endif %}

		{% if invitations %}
			<div class="soirees__heading"><h2>... auxquelles je suis invité(e)</h2></div>
			<div class="soirees__content">
				{% for soiree in invitations %}
					<div class="soiree">
						<div class="soiree__heading">
							<h2>{{ soiree.date|week_day }} {{ soiree.date.day }} {{ soiree.date|month_str }} {{ soiree.date.year }}</h2>
						</div>
						<div class="soiree__content">
							<div class="soiree__fig">
								<div class="soiree__imgwrapper">
									{% if soiree.has_image %}
										<img src="{{ soiree.image.url }}">
									{% else %}
										<img src="{% static 'soiree/images/default_image.jpg' %}">
									{% endif %}
								</div>
							</div>
							<div class="soiree__txt">
								<p class="lieu">{{ soiree.lieu.name }}</p>
								<div class="soiree__buttons">
									<a href="{% url 'soiree:inscription' %}?id={{soiree.id}}"><img src="{% static 'soiree/images/green_check.png' %}"></a>
									<a href="{% url 'soiree:desinscription' %}?id={{soiree.id}}"><img src="{% static 'soiree/images/red_cross.png' %}"></a>
								</div>
							</div>						
						</div>
					</div>
				{% endfor %}
			</div>
		{% endif %}

	</div>
{% endblock %}