sept_tadelles/sept_tadelles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('welcome.urls')),
    path('wiki/', include('wiki.urls')),
    path('account/', include('account.urls')),
    path('soiree/', include('soiree.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sept_tadelles/soiree/urls.py
from django.urls import path

from . import views

app_name = "soiree"
urlpatterns = [
    path("list", views.list, name="list"),
    path("detail", views.detail, name="detail"),
    path("creation-1", views.creation_step_1, name="creation_step_1"),
    path("creation-2", views.creation_step_2, name="creation_step_2"),
    path("creation-3", views.creation_step_3, name="creation_step_3"),
    path("creation-4", views.creation_step_4, name="creation_step_4"),
    path("invites", views.change_invites, name="change_invites"),
    path("inscription", views.inscription, name="inscription"),
    path("desinscription", views.desinscription, name="desinscription"),
    path("delete", views.delete_soiree, name="delete_soiree"),
]

sept_tadelles/welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.index, name="index"),
]

sept_tadelles/wiki/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:game_id>/", views.detail, name="detail"),
]

sept_tadelles/welcome/models.py
from django.db import models

# Create your models here.

sept_tadelles/welcome/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail

from account.views import helpers

# Create your views here.

def index(request) :

    current_view = ['welcome:index', []]
    real_view = True

    btn_list = []
    if request.user.is_authenticated :
        btn_list = [
            ("déconnexion", "account:logout", "", ()),
            ("mon compte", "account:detail", f"?id={request.user.id}", ())
        ]
    else :
        btn_list = [("connexion", "account:login", "", ())]

    helpers.register_view(request, current_view)
    return render(request, 'welcome/index.html', {"buttons": btn_list})

sept_tadelles/welcome/templates/welcome/index.html
<!DOCTYPE html>

{% load static %}

<html>
	<head>
		<title>7tadelles</title>
		<link rel="icon" href="{% static 'welcome/7tadelles_icon.png' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'welcome/style.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
	</head>
<body>

	<header>

		<div class="centre">
			<a href="{% url 'soiree:list' %}" class="btn">SOIRÉES</a>
			<a href="{% url 'wiki:index' %}" class="btn">JEUX</a>
		</div>

	</header>

	<div class="background">
		<div class="text"></div>
	</div>

	<div class="foreground">

		<div class="foreground__btnbar">
			{% for button in buttons %}
				{% if button.3 %}
			        {% with bouton_args=button.3 %}
			            <div class="foreground__btn"><a href="{% url button.1 bouton_args %}{{button.2}}"><p>{{ button.0 }}</p></a></div>
			        {% endwith %}
			    {% else %}
			        <div class="foreground__btn"><a href="{% url button.1 %}{{button.2}}"><p>{{ button.0 }}</p></a></div>
			    {% endif %}
			{% endfor %}
		</div>



		{% if user.is_authenticated %}
			<div class="title"><h1>Bienvenue, {{ user.get_username }}</h1></div>
		{% else %}
			<div class="title"><h1>7TADELLES</h1></div>
		{% endif %}
		<div class="description">
			<p>
				Bienvenue sur 7tadelles. Ce site est imaginé et développé par un apprenti développeur passionné de jeux de société, pour des passionnés de jeux de société.
			</p>
			<p>
				Sur ce site, vous pourrez :
				<ul>
					<li>Vous renseigner sur des jeux de société</li>
					<li>Vous faire de nouveaux amis (qui sait ?)</li>
					<li>Organiser des soirées jeux avec vos amis</li>
					<li>Participer aux soirées jeux auxquelles vous êtes invité</li>
				</ul>
			</p>
			<p>
				Vous pourrez peut-être bientôt :
				<ul>
					<li>Discuter avec d'autres joueurs</li>
					<li>Profiter d'un générateur d'équipes</li>
				</ul>
			</p>
			<p>
				Cependant vous ne pourrez pas :
				<ul>
					<li>Commander des pizzas pour manger entre deux parties</li>
					<li>Acheter des jeux de société (pour ça va falloir aller ailleurs)</li>
				</ul>
			</p>
			<p>
				Si vous avez des suggestions de fonctionnalités à ajouter au site, ou si vous rencontrez un bug ou si vous voulez me dire à quel point vous aimez ce site :), n'hésitez pas à m'envoyer un mail à contact@7tadelles.com.
			</p>
			<p>
				Ce site n'est pas très adapté pour être visité depuis autre chose qu'un ordinateur donc si vous le visitez depuis votre smartphone, je suis sincèrement désolé pour ce que vous voyez.				
			</p>
			<p>Bonne visite ;)</p>
		</div>
	</div>

	<footer>
		<div class="bottom-right"><p>v4.2.1</p></div>
	</footer>

</body>
</html>